# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abc5aa4ab1c1a9d7d5fa780a07b9834a25b4918db5186d2c14af1935b5860370cd2a06d78f1abcfc4df4fd1ae60ef3ee618aff78c917388b099c3cbe1a6564f3

test:
  secret_key_base: 4869e250be75d2a2a3ed755e28afdc9cfb7f2ae1596d38014020480315390b5717e01aead75dc67da7c0880e195f8db322e786fc55c022ef8ccf9fb97bbcf3dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
